-- AlterTable
ALTER TABLE "RateConfig" ADD COLUMN "minWithdrawalNgn" DECIMAL(20,2) NOT NULL DEFAULT 5000;
ALTER TABLE "RateConfig" ADD COLUMN "minWithdrawalGhs" DECIMAL(20,2) NOT NULL DEFAULT 50;
ALTER TABLE "RateConfig" ADD COLUMN "minWithdrawalUsdt" DECIMAL(20,6) NOT NULL DEFAULT 5;
