/** Official website domain per card slug (used for logo fetching and favicon fallback). */
export const CARD_BRAND_DOMAINS: Record<string, string> = {
  "adidas-gift-card": "adidas.com",
  "airbnb-gift-card": "airbnb.com",
  "aldi-gift-card": "aldi.us",
  amazon: "amazon.com",
  "amc-theaters-gift-card": "amctheatres.com",
  "american-apparel-gift-card": "americanapparel.net",
  "american-express-gift-card": "americanexpress.com",
  "americanas-gift-card": "americanas.com.br",
  "apex-legends-gift-card": "ea.com",
  "apple-gift-card-us-only": "apple.com",
  "apple-itunes": "apple.com",
  "apple-store-gift-card": "apple.com",
  "applebee-s-restaurant-gift-card": "applebees.com",
  "arcteryx-gift-card": "arcteryx.com",
  "argoss-gift-card": "argos.co.uk",
  "asos-gift-card": "asos.com",
  "at-t-gift-card": "att.com",
  "barnes-noble-gift-card": "barnesandnoble.com",
  "bed-bath-beyond-gift-card": "bedbathandbeyond.com",
  "best-buy-gift-card": "bestbuy.com",
  "bitjem-gift-card": "bitjem.com",
  "bitrefill-balance-cards": "bitrefill.com",
  "bitsa-visa-gift-card": "bitsa.com",
  "blizzard-gift-card": "battle.net",
  "booking-com-gift-cards": "booking.com",
  "boost-mobile": "boostmobile.com",
  "build-a-bear": "buildabear.com",
  "cabela-s-e-gift-code": "cabelas.com",
  "calvin-klein-gift-card": "calvinklein.com",
  "cashlib-vouchers": "cashlib.com",
  "cashtocode-voucher": "cashtocode.com",
  "chime-mail": "chime.com",
  "cineworld-gift-card": "cineworld.co.uk",
  "coles-gift-card": "coles.com.au",
  "costco-cash-card": "costco.com",
  "crypto-voucher": "cryptovoucher.io",
  "cvs-gift-card": "cvs.com",
  "cvs-pharmacy": "cvs.com",
  "david-jones": "davidjones.com",
  "delta-air-line-gift-card": "delta.com",
  "dicks-gift-cards": "dickssportinggoods.com",
  "discord-gift-card": "discord.com",
  "disney-gift-cards": "disney.com",
  "dollar-general": "dollargeneral.com",
  "domino-s-pizza-gift-card": "dominos.com",
  doordash: "doordash.com",
  "ea-play-gift-card": "ea.com",
  ebay: "ebay.com",
  "egifter-com-code": "egifter.com",
  "eneba-gift-card": "eneba.com",
  "flexepin-gift-card": "flexepin.com",
  "flipkart-e-gift-voucher": "flipkart.com",
  footlocker: "footlocker.com",
  "footlocker-sports-gift-card": "footlocker.com",
  "fortnite-vbucks": "epicgames.com",
  gamestop: "gamestop.com",
  "gap-gift": "gap.com",
  "gift-cards-miscellaneous-retailers": "giftcards.com",
  google: "google.com",
  "google-play-gift-card": "play.google.com",
  "grubhub-gift-card": "grubhub.com",
  "h-m-gift-card": "hm.com",
  "hema-gift-card": "hema.com",
  "home-depot-gift-card": "homedepot.com",
  "hotels-com-gift-card": "hotels.com",
  "ikea-gift-card": "ikea.com",
  "imo-gift-card": "imo.im",
  "imvu-gift-card": "imvu.com",
  "instacart-gift-card": "instacart.com",
  "itunes-gift-card": "apple.com",
  "jawaker-pins-card": "jawaker.com",
  "jd-com-gift-cards": "jd.com",
  "kohls-store-gift-card": "kohls.com",
  "league-of-legends-teamfight-tactics-gift-card": "leagueoflegends.com",
  "lowe-s-gift-card": "lowes.com",
  lowes: "lowes.com",
  "lululemon-gift-card": "lululemon.com",
  "lyft-gift-card": "lyft.com",
  "m-s-gift-card": "marksandspencer.com",
  macy: "macys.com",
  "macy-s-gift-card": "macys.com",
  "mastercard-gift-card": "mastercard.com",
  "microsoft-gift-card": "microsoft.com",
  moneypak: "moneypak.com",
  "my-prepaid-center": "myprepaidcenter.com",
  "myer-gift-card": "myer.com.au",
  "myvanilla-prepaid-card": "myvanilla.com",
  "neosurf-gift-card": "neosurf.com",
  "netflix-gift-card": "netflix.com",
  "nexon-game-card": "nexon.com",
  nike: "nike.com",
  "nintendo-eshop-card-gift-card": "nintendo.com",
  nordstrom: "nordstrom.com",
  "nordvpn-subscription": "nordvpn.com",
  "office-depot-gift-card": "officedepot.com",
  "old-navy-e-gift-card": "oldnavy.com",
  "olive-garden-restaurant-gift-card": "olivegarden.com",
  "one4all-card": "one4all.com",
  "onevanilla-visa-mastercard-gift-card": "onevanilla.com",
  "ozon-gift-card": "ozon.ru",
  "papa-johns-gift-card": "papajohns.com",
  "pcs-prepaid-cash-services": "pcsprepaid.com",
  playstation: "playstation.com",
  "playstation-network-gift-card": "playstation.com",
  "r2-games-coins": "r2games.com",
  razer: "razer.com",
  "razer-gold-gift-card": "razer.com",
  "restaurant-gift-cards-various-retailers": "giftcards.com",
  roblox: "roblox.com",
  "roblox-game-card": "roblox.com",
  "saks-fifth-avenue-gift-card": "saksfifthavenue.com",
  sephora: "sephora.com",
  "skype-credits": "skype.com",
  "southwest-airlines-gift-card": "southwest.com",
  "starbucks-card": "starbucks.com",
  steam: "steampowered.com",
  "steam-wallet-gift-card": "steampowered.com",
  "subway-gift-card": "subway.com",
  "superdry-gift-card": "superdry.com",
  "t-mobile-refill": "t-mobile.com",
  "target-gift-card": "target.com",
  "target-visa-gift-card": "target.com",
  tesco: "tesco.com",
  "ticketmaster-gift-card": "ticketmaster.com",
  "tinder-gift-card": "tinder.com",
  "tmall-gift-card": "tmall.com",
  "transcash-voucher": "transcash.me",
  "uber-eats": "ubereats.com",
  "uber-gift-card": "uber.com",
  "ulta-gift-card": "ulta.com",
  "united-airlines-gift-card": "united.com",
  "upi-voucher": "npci.org.in",
  "valorant-gift-card": "playvalorant.com",
  vanilla: "vanillagift.com",
  "victoria-s-secret-gift-card": "victoriassecret.com",
  visa: "visa.com",
  walmart: "walmart.com",
  "walmart-china-card": "walmart.cn",
  "walmart-visa-gift-card": "walmart.com",
  "wildberries-gift-card": "wildberries.ru",
  wunschgutschein: "wunschgutschein.de",
  "x-box": "xbox.com",
  "xbox-gift-card": "xbox.com",
  "zappos-gift-card": "zappos.com",
};

/** Simple Icons CDN slug when it differs from our card slug stem. */
export const SIMPLE_ICON_SLUGS: Record<string, string> = {
  "apex-legends-gift-card": "ea",
  "at-t-gift-card": "att",
  "blizzard-gift-card": "blizzard",
  "chime-mail": "chime",
  "cvs-pharmacy": "cvs",
  "ea-play-gift-card": "ea",
  "fortnite-vbucks": "epicgames",
  "google-play-gift-card": "googleplay",
  "h-m-gift-card": "handm",
  "itunes-gift-card": "itunes",
  "league-of-legends-teamfight-tactics-gift-card": "leagueoflegends",
  "m-s-gift-card": "marksandspencer",
  "macy-s-gift-card": "macys",
  "playstation-network-gift-card": "playstation",
  "razer-gold-gift-card": "razer",
  "steam-wallet-gift-card": "steam",
  "t-mobile-refill": "tmobile",
  "uber-eats": "ubereats",
  "valorant-gift-card": "riotgames",
  "x-box": "xbox",
};

const SLUG_SUFFIX =
  /(?:-gift-cards?|-e-gift-card|-cash-card|-prepaid-card|-vouchers?|-coins|-credits|-refill|-subscription|-code|-balance-cards|-pins-card|-miscellaneous-retailers|-various-retailers|-us-only)$/i;

export function cardSlugStem(slug: string): string {
  return slug.replace(SLUG_SUFFIX, "");
}

export function brandDomainForSlug(slug: string): string {
  if (CARD_BRAND_DOMAINS[slug]) return CARD_BRAND_DOMAINS[slug];
  const stem = cardSlugStem(slug);
  if (CARD_BRAND_DOMAINS[stem]) return CARD_BRAND_DOMAINS[stem];
  return `${stem.split("-")[0]}.com`;
}

export function simpleIconSlugForCard(slug: string): string {
  if (SIMPLE_ICON_SLUGS[slug]) return SIMPLE_ICON_SLUGS[slug];
  const stem = cardSlugStem(slug);
  if (SIMPLE_ICON_SLUGS[stem]) return SIMPLE_ICON_SLUGS[stem];
  return stem.replace(/-/g, "");
}
