/** ISO 3166-1 alpha-2 codes for flag-icons (lowercase). Keys are normalized labels. */
const COUNTRY_ALIASES: Record<string, string> = {
  us: "us",
  usa: "us",
  "u s": "us",
  "u s a": "us",
  "united states": "us",
  "united states of america": "us",
  america: "us",

  uk: "gb",
  "u k": "gb",
  "united kingdom": "gb",
  britain: "gb",
  "great britain": "gb",
  england: "gb",
  gbp: "gb",

  euro: "eu",
  eu: "eu",
  eur: "eu",
  europe: "eu",
  "euro zone": "eu",
  "eurozone": "eu",
  germany: "de",
  france: "fr",
  italy: "it",
  spain: "es",
  netherlands: "nl",
  holland: "nl",
  sweden: "se",
  norway: "no",
  denmark: "dk",
  ireland: "ie",
  austria: "at",
  belgium: "be",
  portugal: "pt",
  finland: "fi",
  greece: "gr",
  switzerland: "ch",
  poland: "pl",

  canada: "ca",
  cad: "ca",
  australia: "au",
  aud: "au",
  china: "cn",
  cny: "cn",
  india: "in",
  inr: "in",
  japan: "jp",
  jpy: "jp",
  singapore: "sg",
  sgp: "sg",
  "new zealand": "nz",
  nzd: "nz",
  mexico: "mx",
  mxn: "mx",
  brazil: "br",
  brl: "br",
  "hong kong": "hk",
  hkd: "hk",
  "south korea": "kr",
  korea: "kr",
  krw: "kr",
  malaysia: "my",
  myr: "my",
  philippines: "ph",
  php: "ph",
  thailand: "th",
  thb: "th",
  uae: "ae",
  "united arab emirates": "ae",
  aed: "ae",
  "saudi arabia": "sa",
  sar: "sa",
  turkey: "tr",
  try: "tr",
  russia: "ru",
  rub: "ru",
  indonesia: "id",
  idr: "id",
  vietnam: "vn",
  vnd: "vn",
  taiwan: "tw",
  twd: "tw",
  israel: "il",
  ils: "il",
  "south africa": "za",
  zar: "za",
  nigeria: "ng",
  ngn: "ng",
  ghana: "gh",
  ghs: "gh",
  egypt: "eg",
  egp: "eg",
  argentina: "ar",
  ars: "ar",
  colombia: "co",
  cop: "co",
  chile: "cl",
  clp: "cl",
  peru: "pe",
  pen: "pe",
  pakistan: "pk",
  pkr: "pk",
  bangladesh: "bd",
  bdt: "bd",
  "czech republic": "cz",
  czechia: "cz",
  czk: "cz",
  hungary: "hu",
  huf: "hu",
  romania: "ro",
  ron: "ro",
  ukraine: "ua",
  uah: "ua",
  qatar: "qa",
  qar: "qa",
  kuwait: "kw",
  kwd: "kw",
  bahrain: "bh",
  bhd: "bh",
  oman: "om",
  omr: "om",
  jordan: "jo",
  jod: "jo",
  lebanon: "lb",
  lbp: "lb",
  morocco: "ma",
  mad: "ma",
  kenya: "ke",
  kes: "ke",
  ethiopia: "et",
  etb: "et",
  cameroon: "cm",
  xaf: "cm",
  senegal: "sn",
  xof: "sn",
  luxembourg: "lu",
  iceland: "is",
  isk: "is",
  croatia: "hr",
  hrk: "hr",
  serbia: "rs",
  rsd: "rs",
  bulgaria: "bg",
  bgn: "bg",
  slovakia: "sk",
  slovenia: "si",
  estonia: "ee",
  latvia: "lv",
  lithuania: "lt",
  cyprus: "cy",
  malta: "mt",
  monaco: "mc",
  liechtenstein: "li",
  andorra: "ad",
  uruguay: "uy",
  uyu: "uy",
  paraguay: "py",
  pyp: "py",
  bolivia: "bo",
  bob: "bo",
  ecuador: "ec",
  "costa rica": "cr",
  crc: "cr",
  panama: "pa",
  pab: "pa",
  guatemala: "gt",
  gtq: "gt",
  "dominican republic": "do",
  dop: "do",
  jamaica: "jm",
  jmd: "jm",
  trinidad: "tt",
  ttd: "tt",
  bahamas: "bs",
  bsd: "bs",
  barbados: "bb",
  bbd: "bb",
  bermuda: "bm",
  bmd: "bm",
  cayman: "ky",
  kyd: "ky",
  macau: "mo",
  mop: "mo",
  macao: "mo",
  cambodia: "kh",
  khr: "kh",
  laos: "la",
  lak: "la",
  myanmar: "mm",
  mmk: "mm",
  burma: "mm",
  nepal: "np",
  npr: "np",
  "sri lanka": "lk",
  lkr: "lk",
  mongolia: "mn",
  mnt: "mn",
  kazakhstan: "kz",
  kzt: "kz",
  uzbekistan: "uz",
  uzs: "uz",
  azerbaijan: "az",
  azn: "az",
  georgia: "ge",
  gel: "ge",
  armenia: "am",
  amd: "am",
  belarus: "by",
  byn: "by",
  moldova: "md",
  mdl: "md",
  albania: "al",
  "north macedonia": "mk",
  mkd: "mk",
  macedonia: "mk",
  bosnia: "ba",
  bam: "ba",
  montenegro: "me",
  kosovo: "xk",
  chf: "ch",
  usd: "us",
};

/** Non-standard 2-letter labels → ISO 3166-1 alpha-2. */
const TWO_LETTER_OVERRIDES: Record<string, string> = {
  uk: "gb",
  el: "gr",
  sf: "fi",
  en: "gb",
};

function normalizeCountryKey(country: string): string {
  return country
    .trim()
    .toLowerCase()
    .replace(/\./g, "")
    .replace(/\s+/g, " ");
}

/**
 * Resolve a flag-icons ISO code for a card country label.
 * Returns null for "Other" (no single country flag).
 */
export function resolveFlagIso(country: string, currency?: string): string | null {
  if (!country || country === "Other") return null;

  const key = normalizeCountryKey(country);
  const alias = COUNTRY_ALIASES[key];
  if (alias) return alias;

  if (/^[a-z]{2}$/i.test(country.trim())) {
    const code = country.trim().toLowerCase();
    return TWO_LETTER_OVERRIDES[code] ?? code;
  }

  if (currency) {
    const cur = normalizeCountryKey(currency);
    const fromCurrency = COUNTRY_ALIASES[cur];
    if (fromCurrency) return fromCurrency;
  }

  // Last resort: first token (e.g. "Hong Kong SAR" → "hong")
  const firstToken = key.split(" ")[0];
  if (firstToken && COUNTRY_ALIASES[firstToken]) return COUNTRY_ALIASES[firstToken];

  return null;
}

export function flagSvgPath(iso: string): string {
  return `/flags/4x3/${iso}.svg`;
}
